
package com.soap.selfmadecalculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorImplement", targetNamespace = "hhtp://CalcWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorImplement {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "hhtp://CalcWS", className = "com.soap.selfmadecalculator.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "hhtp://CalcWS", className = "com.soap.selfmadecalculator.AddResponse")
    @Action(input = "hhtp://CalcWS/CalculatorImplement/addRequest", output = "hhtp://CalcWS/CalculatorImplement/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "hhtp://CalcWS", className = "com.soap.selfmadecalculator.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "hhtp://CalcWS", className = "com.soap.selfmadecalculator.DivideResponse")
    @Action(input = "hhtp://CalcWS/CalculatorImplement/divideRequest", output = "hhtp://CalcWS/CalculatorImplement/divideResponse")
    public int divide(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "hhtp://CalcWS", className = "com.soap.selfmadecalculator.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "hhtp://CalcWS", className = "com.soap.selfmadecalculator.MultiplyResponse")
    @Action(input = "hhtp://CalcWS/CalculatorImplement/multiplyRequest", output = "hhtp://CalcWS/CalculatorImplement/multiplyResponse")
    public int multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "hhtp://CalcWS", className = "com.soap.selfmadecalculator.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "hhtp://CalcWS", className = "com.soap.selfmadecalculator.SubtractResponse")
    @Action(input = "hhtp://CalcWS/CalculatorImplement/subtractRequest", output = "hhtp://CalcWS/CalculatorImplement/subtractResponse")
    public int subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
