
package com.soap.selfmadecalculator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorImplementService", targetNamespace = "hhtp://CalcWS", wsdlLocation = "http://localhost:8080/CalculatorWS/Calculator?wsdl")
public class CalculatorImplementService
    extends Service
{

    private final static URL CALCULATORIMPLEMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORIMPLEMENTSERVICE_EXCEPTION;
    private final static QName CALCULATORIMPLEMENTSERVICE_QNAME = new QName("hhtp://CalcWS", "CalculatorImplementService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CalculatorWS/Calculator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORIMPLEMENTSERVICE_WSDL_LOCATION = url;
        CALCULATORIMPLEMENTSERVICE_EXCEPTION = e;
    }

    public CalculatorImplementService() {
        super(__getWsdlLocation(), CALCULATORIMPLEMENTSERVICE_QNAME);
    }

    public CalculatorImplementService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORIMPLEMENTSERVICE_QNAME, features);
    }

    public CalculatorImplementService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORIMPLEMENTSERVICE_QNAME);
    }

    public CalculatorImplementService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORIMPLEMENTSERVICE_QNAME, features);
    }

    public CalculatorImplementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorImplementService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorImplement
     */
    @WebEndpoint(name = "CalculatorImplementPort")
    public CalculatorImplement getCalculatorImplementPort() {
        return super.getPort(new QName("hhtp://CalcWS", "CalculatorImplementPort"), CalculatorImplement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorImplement
     */
    @WebEndpoint(name = "CalculatorImplementPort")
    public CalculatorImplement getCalculatorImplementPort(WebServiceFeature... features) {
        return super.getPort(new QName("hhtp://CalcWS", "CalculatorImplementPort"), CalculatorImplement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORIMPLEMENTSERVICE_EXCEPTION!= null) {
            throw CALCULATORIMPLEMENTSERVICE_EXCEPTION;
        }
        return CALCULATORIMPLEMENTSERVICE_WSDL_LOCATION;
    }

}
