
package com.soap.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LibraryWSService", targetNamespace = "http://ws", wsdlLocation = "http://localhost:8080/2021_L2_03_ws/services/LibraryWS?wsdl")
public class LibraryWSService
    extends Service
{

    private final static URL LIBRARYWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LIBRARYWSSERVICE_EXCEPTION;
    private final static QName LIBRARYWSSERVICE_QNAME = new QName("http://ws", "LibraryWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/2021_L2_03_ws/services/LibraryWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBRARYWSSERVICE_WSDL_LOCATION = url;
        LIBRARYWSSERVICE_EXCEPTION = e;
    }

    public LibraryWSService() {
        super(__getWsdlLocation(), LIBRARYWSSERVICE_QNAME);
    }

    public LibraryWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBRARYWSSERVICE_QNAME, features);
    }

    public LibraryWSService(URL wsdlLocation) {
        super(wsdlLocation, LIBRARYWSSERVICE_QNAME);
    }

    public LibraryWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBRARYWSSERVICE_QNAME, features);
    }

    public LibraryWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibraryWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LibraryWS
     */
    @WebEndpoint(name = "LibraryWS")
    public LibraryWS getLibraryWS() {
        return super.getPort(new QName("http://ws", "LibraryWS"), LibraryWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibraryWS
     */
    @WebEndpoint(name = "LibraryWS")
    public LibraryWS getLibraryWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws", "LibraryWS"), LibraryWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBRARYWSSERVICE_EXCEPTION!= null) {
            throw LIBRARYWSSERVICE_EXCEPTION;
        }
        return LIBRARYWSSERVICE_WSDL_LOCATION;
    }

}
